#!/usr/bin/env python3
"""Render a day's thread.md + trends.json into a static site/ page.

Usage: python3 scripts/render.py [YYYY-MM-DD]  (default: today)
Output: site/index.html (latest) + site/<date>/index.html (archive).
Stdlib only. Safe to run from cron after the draft step.
"""
import html
import json
import re
import sys
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent


def parse_tweets(text: str) -> list:
    text = re.sub(r"\r", "", text).strip()
    if not text:
        return []
    # Split on blank lines; fall back to single block.
    parts = [p.strip() for p in re.split(r"\n\s*\n", text) if p.strip()]
    if len(parts) <= 1:
        lines = [l.strip() for l in text.split("\n") if l.strip()]
        parts = lines if len(lines) > 1 else [text]
    return parts


def tweet_card(i: int, n: int, body: str) -> str:
    return (
        f'<article class="tweet"><div class="meta">'
        f"<span>{i}/{n}</span><span>{len(body)}/280</span></div>"
        f"<p>{html.escape(body)}</p></article>"
    )


def page(day: str, tweets: list, topics: list) -> str:
    cards = "\n".join(tweet_card(i + 1, len(tweets), t) for i, t in enumerate(tweets))
    topic_items = "".join(
        f"<li><span class='src'>{html.escape(str(t.get('source', '?')))}</span> "
        f"{html.escape(str(t.get('topic', '')))}</li>" for t in topics[:12]
    )
    return f"""<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Trend Threads — {day}</title>
<style>
:root{{color-scheme:dark}}body{{background:#0b1220;color:#e8eef7;font:16px/1.55 system-ui,sans-serif;margin:0 auto;max-width:640px;padding:24px 16px}}
h1{{font-size:22px}}h2{{font-size:15px;color:#8fa1b8;text-transform:uppercase;letter-spacing:.08em}}
.tweet{{background:#101b30;border:1px solid #1e2c47;border-radius:12px;padding:14px 16px;margin:12px 0}}
.meta{{display:flex;justify-content:space-between;font-size:12px;color:#7d8ea8;margin-bottom:6px}}
ul{{padding-left:18px}}.src{{color:#ffc156;font-size:12px;margin-right:6px}}
footer{{color:#5c6b84;font-size:12px;margin-top:28px}}
a{{color:#4adee6}}
</style></head><body>
<h1>🧵 Trend Threads — {day}</h1>
<h2>Today's draft thread</h2>
{cards or '<p>No draft yet today.</p>'}
<h2>Source topics</h2>
<ul>{topic_items or '<li>—</li>'}</ul>
<footer>Generated by Hermes Studio · drafts, not auto-posted · <a href="../">archive</a></footer>
</body></html>
"""


def archive_index(site: Path, days: list) -> None:
    links = "".join(f'<li><a href="{d}/">{d}</a></li>' for d in sorted(days, reverse=True))
    (site / "index.html").write_text(
        f"<!doctype html><html lang='en'><head><meta charset='utf-8'>"
        f"<meta name='viewport' content='width=device-width,initial-scale=1'>"
        f"<title>Trend Threads archive</title></head><body style='background:#0b1220;"
        f"color:#e8eef7;font:16px system-ui;max-width:640px;margin:0 auto;padding:24px 16px'>"
        f"<h1>🧵 Trend Threads</h1><ul>{links}</ul></body></html>"
    )


def main() -> int:
    day = sys.argv[1] if len(sys.argv) > 1 else date.today().isoformat()
    if not re.fullmatch(r"\d{4}-\d{2}-\d{2}", day):
        print(f"bad date: {day} (want YYYY-MM-DD)")
        return 2
    ddir = ROOT / "data" / day
    thread = ddir / "thread.md"
    trends_f = ddir / "trends.json"
    tweets = parse_tweets(thread.read_text()) if thread.exists() else []
    topics = []
    if trends_f.exists():
        try:
            raw = json.loads(trends_f.read_text())
            if isinstance(raw, dict):
                for v in raw.values():
                    if isinstance(v, list):
                        topics.extend(v)
            elif isinstance(raw, list):
                topics = raw
        except json.JSONDecodeError:
            pass
    outdir = ROOT / "site" / day
    outdir.mkdir(parents=True, exist_ok=True)
    (outdir / "index.html").write_text(page(day, tweets, topics))
    days = [p.name for p in (ROOT / "site").iterdir()
            if p.is_dir() and (p / "index.html").exists()]
    archive_index(ROOT / "site", days)
    print(f"rendered {day}: {len(tweets)} tweets, {len(topics)} topics → site/{day}/index.html")
    return 0


if __name__ == "__main__":
    sys.exit(main())
